language: c
# we need more depth for git describe
git:
  depth: false
matrix:
  include:
    - compiler: gcc
      env: SOAPYSDR=ON
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - curl
            - automake
            - libtool
            - libudev-dev
            - pkg-config
            - checkinstall 
            - ruby-dev 
            - rubygems 
            - rpm
       before_install:
        - gem install --no-ri --no-rdoc fpm
       script:
        - chmod ugo+x build-rtl_433-linux.sh
        - ./build-rtl_433-linux.sh
        - cp ./description-pak ${TRAVIS_BUILD_DIR}/build/description-pak
        - cd ${TRAVIS_BUILD_DIR}/src/rtl_433/build
        - checkinstall --install=no --pkgname=rtl_433 --pkgversion=`date +%Y%m%d` --pkgarch=amd64 --pkgrelease=git --pkglicense=GPL2 --pkggroup=Productivity/Hamradio/Other --maintainer="Gergely\ Kun\ \<kun.gergely\@kgservermanagement.com\>" --nodoc -y
        - fpm -s deb -t rpm rtl-433_`date +%Y%m%d`-git_amd64.deb 
       before_deploy:
        - git config --local user.name "Kungergely"
        - git config --local user.email "kun.gergely@kgservermanagement.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: rtl-433_`date +%Y%m%d`-git_amd64.deb
          skip_cleanup: true
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: rtl-433-`date +%Y%m%d`-git.x86-64.rpm
          skip_cleanup: true
    - compiler: x86_64-w64-mingw32-gcc
      env: CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ BUILD_HOME=${TRAVIS_BUILD_DIR} CPU_COUNT=$(nproc)
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - curl
            - automake
            - libtool
            - libudev-dev
            - pkg-config
            - zip
            - mingw-w64
      script:
        - mkdir -p $BUILD_HOME/src && mkdir -p $BUILD_HOME/build && mkdir -p $BUILD_HOME/bin && mkdir -p $BUILD_HOME/build/rtl_433
        - cd $BUILD_HOME/src && git clone https://github.com/libusb/libusb.git && cd $BUILD_HOME/src/libusb && ./autogen.sh --prefix="$BUILD_HOME/build" --bindir="$BUILD_HOME/bin" --enable-shared --enable-static --host=x86_64-w64-mingw32 && make -j${CPU_COUNT} && make install
        - cd $BUILD_HOME/src && git clone https://github.com/osmocom/rtl-sdr.git && cd  $BUILD_HOME/src/rtl-sdr && PKG_CONFIG_PATH="$BUILD_HOME/build/lib/pkgconfig" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$BUILD_HOME/build" -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=amd64 && make -j${CPU_COUNT} && make install
        - cd $BUILD_HOME/build/lib && rm -rf *.dll* && mv librtlsdr_static.a librtlsdr.a && cd $BUILD_HOME/build/bin && rm -rf *.dll* && cd $BUILD_HOME/src && git clone https://github.com/merbanan/rtl_433.git && cd  $BUILD_HOME/src/rtl_433 && mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$BUILD_HOME/build/rtl_433" -DLIBUSB_INCLUDE_DIR="$BUILD_HOME/build/include/libusb-1.0" -DENABLE_RTLSDR=ON -DENABLE_SOAPYSDR=OFF  -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=amd64 .. && make -j${CPU_COUNT} && make install
        - cd $BUILD_HOME/build && zip --symlinks rtl_433_`date +%Y%m%d`-win64.zip rtl_433
      before_deploy:
        - git config --local user.name "Kungergely"
        - git config --local user.email "kun.gergely@kgservermanagement.com"
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d')-$(git log --format=%h -1)}
        - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: rtl_433_`date +%Y%m%d`-win64.zip
        skip_cleanup: true
 
